language: rust
addons:
  apt:
    packages:
      - libssl-dev

cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test --verbose
  - rustup component add clippy && cargo clippy --all-targets || echo "no clippy"

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
